In [1]:
import numpy as np

a=np.array([1,2,3,4,5,6])

In [2]:
a.ndim

1

In [3]:
a.shape

(6,)

In [4]:
a.size

6

In [5]:
a.dtype

dtype('int32')

In [6]:
a.itemsize 

4

In [7]:
b=a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b.ndim

2

In [9]:
b.shape

(2, 3)

In [10]:
b.size

6

In [11]:
b.dtype

dtype('int32')

In [12]:

liste = [1, 2, 3, 4, 5]
dizi1 = np.array(liste)


In [13]:

sifir_dizi = np.zeros((3, 3)) 

sifir_dizi

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:

bir_dizi = np.ones((2, 4)) 
bir_dizi

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
sabit_dizi=np.full((2,2),7) 
sabit_dizi

array([[7, 7],
       [7, 7]])

In [16]:

aralik_dizi = np.arange(0, 10, 2)
aralik_dizi

array([0, 2, 4, 6, 8])

In [17]:

rastgele_dizi = np.random.rand(3, 3)
rastgele_dizi

array([[0.44610301, 0.55911807, 0.69884076],
       [0.52659224, 0.56645906, 0.56776923],
       [0.39324371, 0.52784582, 0.83897542]])

In [18]:

aralik_dizi_2 = np.linspace(0, 10, 5)
aralik_dizi_2

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
x=np.array([1.0,2.0])
x.dtype

dtype('float64')

In [21]:
x=np.array([1,2], dtype=np.int64)
x.dtype

dtype('int64')

In [22]:
x=np.array([.1,2,3])
x.dtype

dtype('float64')

In [23]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
b=a[:2] 
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
b=a[:2,1:3] 
b

array([[2, 3],
       [6, 7]])

In [26]:
b[0,0]=77 
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
x=np.arange(10)*2
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
x[:9:3]=50 
x

array([50,  2,  4, 50,  8, 10, 50, 14, 16, 18])

In [29]:
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
a[-1]

array([ 9, 10, 11, 12])

In [31]:
a[2,:] 

array([ 9, 10, 11, 12])

In [32]:
a[:,-1] 

array([ 4,  8, 12])

In [33]:
for i in a: 
    print (i)

[ 1 77  3  4]
[5 6 7 8]
[ 9 10 11 12]


In [34]:
x=np.array([[1,2],[3,4],[5,6]])
x[[0,1,2],[0,1,0]] 

array([1, 4, 5])

In [35]:
y=np.array([x[0,0],x[1,1],x[2,0]]) 
y

array([1, 4, 5])

In [36]:
y=np.array([x[0,0],x[0,0]]) 
y

array([1, 1])

In [37]:


x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y=np.array([0,2,0,1])

x[np.arange(4),y] 


array([ 1,  6,  7, 11])

In [38]:
x[np.arange(4),y] +=10 
x

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

In [39]:
bool_index=(x>5) 
bool_index

array([[ True, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [40]:
x[x>5] 

array([11, 16, 17,  8,  9, 10, 21, 12])

In [41]:
a=np.array([[2,4,6],[7,1,9]])
b=np.array([[8,3,2],[1,6,0]])

In [42]:
np.vstack((a,b)) 

array([[2, 4, 6],
       [7, 1, 9],
       [8, 3, 2],
       [1, 6, 0]])

In [43]:
np.hstack((a,b)) 

array([[2, 4, 6, 8, 3, 2],
       [7, 1, 9, 1, 6, 0]])

In [44]:
a

array([[2, 4, 6],
       [7, 1, 9]])

In [45]:
b

array([[8, 3, 2],
       [1, 6, 0]])

In [46]:
a+b 

array([[10,  7,  8],
       [ 8,  7,  9]])

In [47]:
np.add(a,b)

array([[10,  7,  8],
       [ 8,  7,  9]])

In [48]:
a-b

array([[-6,  1,  4],
       [ 6, -5,  9]])

In [49]:
np.subtract(a,b)

array([[-6,  1,  4],
       [ 6, -5,  9]])

In [50]:
a*b

array([[16, 12, 12],
       [ 7,  6,  0]])

In [51]:
np.multiply(a,b)

array([[16, 12, 12],
       [ 7,  6,  0]])

In [ ]:
a/b 

In [53]:


vektör1=np.array([9,10])
vektör2=np.array([11,12])


vektör1.dot(vektör2) 

219