In [6]:
import numpy as np

a=np.array([1,2,3,4,5,6])

In [7]:
a.ndim

1

In [9]:
a.shape

(6,)

In [10]:
a.size

6

In [11]:
a.dtype

dtype('int32')

In [26]:
a.itemsize 

4

In [28]:
b=a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b.ndim

2

In [31]:
b.shape

(2, 3)

In [33]:
b.size

6

In [34]:
b.dtype

dtype('int32')

In [17]:

liste = [1, 2, 3, 4, 5]
dizi1 = np.array(liste)


In [21]:

sifir_dizi = np.zeros((3, 3)) 

sifir_dizi

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:

bir_dizi = np.ones((2, 4)) 
bir_dizi

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
sabit_dizi=np.full((2,2),7) 
sabit_dizi

array([[7, 7],
       [7, 7]])

In [23]:

aralik_dizi = np.arange(0, 10, 2)
aralik_dizi

array([0, 2, 4, 6, 8])

In [24]:

rastgele_dizi = np.random.rand(3, 3)
rastgele_dizi

array([[0.7066746 , 0.07524105, 0.08745968],
       [0.19490639, 0.49261806, 0.30772164],
       [0.46593129, 0.67350469, 0.11206845]])

In [25]:

aralik_dizi_2 = np.linspace(0, 10, 5)
aralik_dizi_2

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [44]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
x=np.array([1.0,2.0])
x.dtype

dtype('float64')

In [39]:
x=np.array([1,2], dtype=np.int64)
x.dtype

dtype('int64')

In [40]:
x=np.array([.1,2,3])
x.dtype

dtype('float64')

In [46]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
b=a[:2] 
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
b=a[:2,1:3] 
b

array([[2, 3],
       [6, 7]])

In [52]:
b[0,0]=77 
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
x=np.arange(10)*2
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
x[:9:3]=50 
x

array([50,  2,  4, 50,  8, 10, 50, 14, 16, 18])

In [58]:
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
a[-1]

array([ 9, 10, 11, 12])

In [63]:
a[2,:] 

array([ 9, 10, 11, 12])

In [62]:
a[:,-1] 

array([ 4,  8, 12])

In [65]:
for i in a: 
    print (i)

[ 1 77  3  4]
[5 6 7 8]
[ 9 10 11 12]


In [66]:
x=np.array([[1,2],[3,4],[5,6]])
x[[0,1,2],[0,1,0]] 

array([1, 4, 5])

In [71]:
y=np.array([x[0,0],x[1,1],x[2,0]]) 
y

array([1, 4, 5])

In [73]:
y=np.array([x[0,0],x[0,0]]) 
y

array([1, 1])

In [75]:


x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y=np.array([0,2,0,1])

x[np.arange(4),y] 


array([ 1,  6,  7, 11])

In [77]:
x[np.arange(4),y] +=10 
x

array([[21,  2,  3],
       [ 4,  5, 26],
       [27,  8,  9],
       [10, 31, 12]])

In [79]:
bool_index=(x>5) 
bool_index

array([[ True, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [81]:
x[x>5] 

array([21, 26, 27,  8,  9, 10, 31, 12])

In [94]:
a=np.array([[2,4,6],[7,1,9]])
b=np.array([[8,3,2],[1,6,0]])

In [84]:
np.vstack((a,b)) 

array([[2, 4, 6],
       [7, 1, 9],
       [8, 3, 2],
       [1, 6, 0]])

In [85]:
np.hstack((a,b)) 

array([[2, 4, 6, 8, 3, 2],
       [7, 1, 9, 1, 6, 0]])

In [110]:
a

array([[2, 4, 6],
       [7, 1, 9]])

In [111]:
b

array([[8, 3, 2],
       [1, 6, 0]])

In [92]:
a+b 

array([[10,  7,  8],
       [ 8,  7,  9]])

In [101]:
np.add(a,b)

array([[10,  7,  8],
       [ 8,  7,  9]])

In [103]:
a-b

array([[-6,  1,  4],
       [ 6, -5,  9]])

In [105]:
np.subtract(a,b)

array([[-6,  1,  4],
       [ 6, -5,  9]])

In [106]:
a*b

array([[16, 12, 12],
       [ 7,  6,  0]])

In [107]:
np.multiply(a,b)

array([[16, 12, 12],
       [ 7,  6,  0]])

In [109]:
a/b 

C:\Users\ESMA\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.25      , 1.33333333, 3.        ],
       [7.        , 0.16666667,        inf]])

In [113]:


vektör1=np.array([9,10])
vektör2=np.array([11,12])


vektör1.dot(vektör2) 

219